# Generated by Django 3.0.10 on 2020-09-25 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0003_imagenesproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesproducto',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_producto'),
        ),
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('direccion', models.CharField(max_length=300)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_carrito', to='productos.Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
